import { prisma } from "@/lib/db";
import { auditLog } from "@/lib/auditLog";

interface RuleCondition {
  departmentType?: string;
  outputType?: string;
  priority?: string;
}

interface HandoffActionConfig {
  toTeamType: string;
  title: string;
  priority?: string;
  description?: string;
}

interface ApprovalActionConfig {
  title: string;
  priority?: string;
  decisionType?: string;
  description?: string;
}

export interface HandoffEngineResult {
  handoffsCreated: number;
  approvalsCreated: number;
}

/**
 * Evaluates automation rules after an assignment completes.
 * Creates handoffs and approvals based on matching rules.
 */
export async function runHandoffEngine(opts: {
  assignmentId:  string;
  teamId:        string;
  departmentType: string;
  outputType:    string;
  outputId:      string;
  priority:      string;
  title:         string;
  opportunityId?: string | null;
}): Promise<HandoffEngineResult> {
  const { assignmentId, teamId, departmentType, outputType, outputId, priority, title, opportunityId } = opts;

  // Load opportunity context for richer approvals (if linked)
  let opportunityContext: { title: string; estimatedRevenue: number | null; score: number; confidence: number } | null = null;
  if (opportunityId) {
    try {
      const opp = await prisma.opportunity.findUnique({
        where:  { id: opportunityId },
        select: { title: true, estimatedRevenue: true, score: true, confidence: true },
      });
      opportunityContext = opp;
    } catch { /* non-fatal */ }
  }

  const rules = await prisma.automationRule.findMany({
    where: { trigger: "assignment_completed", active: true },
  });

  let handoffsCreated = 0;
  let approvalsCreated = 0;

  for (const rule of rules) {
    // Evaluate condition
    if (rule.condition) {
      let cond: RuleCondition = {};
      try { cond = JSON.parse(rule.condition) as RuleCondition; } catch { continue; }

      if (cond.departmentType && cond.departmentType !== departmentType) continue;
      if (cond.outputType && cond.outputType !== outputType) continue;
      if (cond.priority && cond.priority !== priority) continue;
    }

    // Execute action
    try {
      if (rule.action === "create_handoff") {
        const config = JSON.parse(rule.actionConfig) as HandoffActionConfig;
        const toTeam = await prisma.workforceTeam.findFirst({
          where: { departmentType: config.toTeamType },
        });
        if (!toTeam) continue;

        await prisma.teamHandoff.create({
          data: {
            fromTeamId:     teamId,
            toTeamId:       toTeam.id,
            title:          config.title.replace("{title}", title),
            description:    config.description?.replace("{title}", title) ?? null,
            status:         "pending",
            relatedOutputId: outputId,
            priority:       config.priority ?? priority,
          },
        });

        await auditLog("assignment", assignmentId, "handoff_created", {
          toTeam: toTeam.name,
          rule: rule.name,
        });

        handoffsCreated++;
      }

      if (rule.action === "create_approval") {
        const config = JSON.parse(rule.actionConfig) as ApprovalActionConfig;
        const sourceTeam = await prisma.workforceTeam.findUnique({ where: { id: teamId } });

        // Build rich approval description (Approval V2)
        const baseDesc = config.description?.replace("{title}", title) ?? null;
        const opportunityLines = opportunityContext
          ? [
              ``,
              `**Opportunity Context:**`,
              `- Opportunity: "${opportunityContext.title}"`,
              `- Score: ${opportunityContext.score}/10 — Confidence: ${opportunityContext.confidence}/10`,
              opportunityContext.estimatedRevenue
                ? `- Estimated Revenue: €${opportunityContext.estimatedRevenue.toLocaleString()}/month`
                : "",
              ``,
              `**What happens if approved:** ${sourceTeam?.name ?? "Team"} will proceed to the next stage of the workflow.`,
              `**What happens if rejected:** Opportunity pauses at this stage for founder review.`,
              `**Risk level:** External action — requires your explicit approval before proceeding.`,
            ].filter(Boolean).join("\n")
          : "";

        await prisma.approval.create({
          data: {
            title:           config.title.replace("{title}", title),
            description:     (baseDesc ?? "") + opportunityLines,
            reason:          `Auto-generated by automation rule: ${rule.name}`,
            status:          "pending",
            sourceTeamId:    teamId,
            relatedOutputId: outputId,
            priority:        config.priority ?? (priority === "urgent" ? "urgent" : "high"),
            decisionType:    config.decisionType ?? "founder_decision",
          },
        });

        await auditLog("assignment", assignmentId, "approval_requested", {
          team: sourceTeam?.name ?? teamId,
          rule: rule.name,
        });

        approvalsCreated++;
      }
    } catch (err) {
      console.error(`[handoff-engine] Rule "${rule.name}" failed:`, err);
    }
  }

  return { handoffsCreated, approvalsCreated };
}
