import { prisma } from "@/lib/db";
import { auditLog } from "@/lib/auditLog";

interface RuleCondition {
  departmentType?: string;
  outputType?: string;
  priority?: string;
}

interface HandoffActionConfig {
  toTeamType: string;
  title: string;
  priority?: string;
  description?: string;
}

interface ApprovalActionConfig {
  title: string;
  priority?: string;
  decisionType?: string;
  description?: string;
}

export interface HandoffEngineResult {
  handoffsCreated: number;
  approvalsCreated: number;
}

/**
 * Evaluates automation rules after an assignment completes.
 * Creates handoffs and approvals based on matching rules.
 */
export async function runHandoffEngine(opts: {
  assignmentId: string;
  teamId: string;
  departmentType: string;
  outputType: string;
  outputId: string;
  priority: string;
  title: string;
}): Promise<HandoffEngineResult> {
  const { assignmentId, teamId, departmentType, outputType, outputId, priority, title } = opts;

  const rules = await prisma.automationRule.findMany({
    where: { trigger: "assignment_completed", active: true },
  });

  let handoffsCreated = 0;
  let approvalsCreated = 0;

  for (const rule of rules) {
    // Evaluate condition
    if (rule.condition) {
      let cond: RuleCondition = {};
      try { cond = JSON.parse(rule.condition) as RuleCondition; } catch { continue; }

      if (cond.departmentType && cond.departmentType !== departmentType) continue;
      if (cond.outputType && cond.outputType !== outputType) continue;
      if (cond.priority && cond.priority !== priority) continue;
    }

    // Execute action
    try {
      if (rule.action === "create_handoff") {
        const config = JSON.parse(rule.actionConfig) as HandoffActionConfig;
        const toTeam = await prisma.workforceTeam.findFirst({
          where: { departmentType: config.toTeamType },
        });
        if (!toTeam) continue;

        await prisma.teamHandoff.create({
          data: {
            fromTeamId:     teamId,
            toTeamId:       toTeam.id,
            title:          config.title.replace("{title}", title),
            description:    config.description?.replace("{title}", title) ?? null,
            status:         "pending",
            relatedOutputId: outputId,
            priority:       config.priority ?? priority,
          },
        });

        await auditLog("assignment", assignmentId, "handoff_created", {
          toTeam: toTeam.name,
          rule: rule.name,
        });

        handoffsCreated++;
      }

      if (rule.action === "create_approval") {
        const config = JSON.parse(rule.actionConfig) as ApprovalActionConfig;
        const sourceTeam = await prisma.workforceTeam.findUnique({ where: { id: teamId } });

        await prisma.approval.create({
          data: {
            title:          config.title.replace("{title}", title),
            description:    config.description?.replace("{title}", title) ?? null,
            reason:         `Auto-generated by automation rule: ${rule.name}`,
            status:         "pending",
            sourceTeamId:   teamId,
            relatedOutputId: outputId,
            priority:       config.priority ?? (priority === "urgent" ? "urgent" : "high"),
            decisionType:   config.decisionType ?? "founder_decision",
          },
        });

        await auditLog("assignment", assignmentId, "approval_requested", {
          team: sourceTeam?.name ?? teamId,
          rule: rule.name,
        });

        approvalsCreated++;
      }
    } catch (err) {
      console.error(`[handoff-engine] Rule "${rule.name}" failed:`, err);
    }
  }

  return { handoffsCreated, approvalsCreated };
}
