import { getAIProvider, isAIEnabled } from "@/lib/ai/provider";
import { getGoalIntelligence, getRevenueIntelligence, getWorkforcePerformance } from "./executive-analysis";
import type { GoalIntelligence, RevenueIntelligence, WorkforcePerformance, Recommendation } from "./executive-analysis";
import { getAllProjectHealth } from "./executive-health";
import { generateRecommendations } from "./executive-recommendations";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface MorningBrief {
  generatedAt: string;
  whatChanged: string[];
  biggestOpportunity: string | null;
  biggestRisk: string | null;
  aiSituation: string | null;
  revenue: RevenueIntelligence;
  goals: GoalIntelligence[];
  workforce: WorkforcePerformance;
  recommendations: Recommendation[];
}

export interface WeeklyReview {
  generatedAt: string;
  periodStart: string;
  periodEnd: string;
  summary: string;
  revenueSnapshot: string;
  goalsStatus: string;
  wins: string[];
  blockers: string[];
  nextWeekFocus: string[];
}

export interface MonthlyReview {
  generatedAt: string;
  month: string;
  summary: string;
  revenueSnapshot: string;
  topAchievements: string[];
  missedTargets: string[];
  keyLearnings: string[];
  nextMonthPriorities: string[];
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function deriveWhatChanged(
  revenue: RevenueIntelligence,
  goals: GoalIntelligence[],
  workforce: WorkforcePerformance,
): string[] {
  const items: string[] = [];
  if (workforce.completedThisWeek > 0) {
    items.push(`${workforce.completedThisWeek} assignment${workforce.completedThisWeek !== 1 ? "s" : ""} completed this week`);
  }
  if (workforce.pendingApprovals > 0) {
    items.push(`${workforce.pendingApprovals} item${workforce.pendingApprovals !== 1 ? "s" : ""} waiting for your approval`);
  }
  const stalledCount = goals.filter(g => g.stalled).length;
  if (stalledCount > 0) {
    items.push(`${stalledCount} goal${stalledCount !== 1 ? "s" : ""} stalled with no recent progress`);
  }
  if (revenue.atRisk.length > 0) {
    items.push(`${revenue.atRisk.length} pipeline deal${revenue.atRisk.length !== 1 ? "s" : ""} at risk`);
  }
  if (workforce.outputsThisWeek > 0) {
    items.push(`${workforce.outputsThisWeek} output${workforce.outputsThisWeek !== 1 ? "s" : ""} generated by your teams this week`);
  }
  if (items.length === 0) {
    items.push("System is operating normally — no urgent issues detected");
  }
  return items;
}

function buildAIContext(
  revenue: RevenueIntelligence,
  goals: GoalIntelligence[],
  workforce: WorkforcePerformance,
  recommendations: Recommendation[],
): string {
  return [
    `Revenue: Live €${Math.round(revenue.live)}/mo | Pipeline €${Math.round(revenue.pipeline)} weighted | ${revenue.atRisk.length} at-risk`,
    `Goals: ${goals.length} active, ${goals.filter(g => g.stalled).length} stalled`,
    `Workforce: ${workforce.totalActiveAssignments} active, ${workforce.completedThisWeek} completed this week, ${workforce.pendingApprovals} pending approvals`,
    `Top priority: ${recommendations[0]?.title ?? "No urgent items"}`,
  ].join("\n");
}

// ── Morning Brief ─────────────────────────────────────────────────────────────

export async function generateMorningBrief(): Promise<MorningBrief> {
  const [revenue, goals, workforce, recommendations, projects] = await Promise.all([
    getRevenueIntelligence(),
    getGoalIntelligence(),
    getWorkforcePerformance(),
    generateRecommendations(),
    getAllProjectHealth(),
  ]);

  const whatChanged = deriveWhatChanged(revenue, goals, workforce);

  const biggestOpportunity = revenue.fastestPath
    ? `${revenue.fastestPath.title} — €${Math.round(revenue.fastestPath.amount)}/mo at ${revenue.fastestPath.probability}% close probability`
    : recommendations.find(r => r.source === "revenue")?.title ?? null;

  const criticalRec = recommendations.find(r => r.priority === "critical");
  const criticalProject = projects.find(p => p.health.status === "critical");
  const biggestRisk = criticalRec
    ? criticalRec.reason
    : criticalProject
    ? `Project "${criticalProject.name}" is in critical health`
    : null;

  let aiSituation: string | null = null;
  if (isAIEnabled()) {
    try {
      const provider = getAIProvider();
      const context = buildAIContext(revenue, goals, workforce, recommendations);
      aiSituation = await provider.generate(
        `You are an executive assistant briefing a startup founder. Write 2-3 concise sentences summarizing today's business situation. Be direct and action-oriented.\n\nCurrent state:\n${context}\n\nSituation summary:`,
      );
    } catch {
      // AI unavailable — no situation text
    }
  }

  return {
    generatedAt: new Date().toISOString(),
    whatChanged,
    biggestOpportunity,
    biggestRisk,
    aiSituation,
    revenue,
    goals,
    workforce,
    recommendations,
  };
}

// ── Weekly Review ─────────────────────────────────────────────────────────────

export async function generateWeeklyReview(): Promise<WeeklyReview> {
  const now = new Date();
  const weekAgo = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);

  const [revenue, goals, workforce, recommendations] = await Promise.all([
    getRevenueIntelligence(),
    getGoalIntelligence(),
    getWorkforcePerformance(),
    generateRecommendations(),
  ]);

  const wins: string[] = [];
  const blockers: string[] = [];
  const nextWeekFocus: string[] = [];

  if (workforce.completedThisWeek > 0) wins.push(`${workforce.completedThisWeek} assignments completed`);
  if (workforce.outputsThisWeek > 0) wins.push(`${workforce.outputsThisWeek} outputs generated by teams`);

  const nearComplete = goals.filter(g => g.progress >= 80 && !g.stalled);
  if (nearComplete.length > 0) wins.push(`${nearComplete.length} goal${nearComplete.length !== 1 ? "s" : ""} near completion (≥80%)`);

  for (const rec of recommendations.filter(r => r.source === "project" && r.priority === "high")) {
    blockers.push(rec.reason);
  }

  for (const rec of recommendations.slice(0, 3)) {
    nextWeekFocus.push(rec.title);
  }

  const summary = [
    `Live revenue: €${Math.round(revenue.live)}/mo with €${Math.round(revenue.pipeline)} weighted in pipeline.`,
    `${goals.filter(g => !g.stalled).length} of ${goals.length} active goals are progressing.`,
    workforce.completedThisWeek > 0
      ? `Teams completed ${workforce.completedThisWeek} assignment${workforce.completedThisWeek !== 1 ? "s" : ""} this week.`
      : "Teams have ongoing work with no completions this week.",
  ].join(" ");

  return {
    generatedAt: now.toISOString(),
    periodStart: weekAgo.toISOString(),
    periodEnd: now.toISOString(),
    summary,
    revenueSnapshot: `Live €${Math.round(revenue.live)}/mo | Pipeline €${Math.round(revenue.pipeline)} | Potential €${Math.round(revenue.potential)}`,
    goalsStatus: `${goals.filter(g => !g.stalled).length} progressing, ${goals.filter(g => g.stalled).length} stalled`,
    wins,
    blockers,
    nextWeekFocus,
  };
}

// ── Monthly Review ────────────────────────────────────────────────────────────

export async function generateMonthlyReview(): Promise<MonthlyReview> {
  const now = new Date();
  const monthName = now.toLocaleDateString("en-GB", { month: "long", year: "numeric" });

  const [revenue, goals, workforce] = await Promise.all([
    getRevenueIntelligence(),
    getGoalIntelligence(),
    getWorkforcePerformance(),
  ]);

  const topAchievements: string[] = [];
  const missedTargets: string[] = [];
  const keyLearnings: string[] = [];
  const nextMonthPriorities: string[] = [];

  if (revenue.live > 0) topAchievements.push(`€${Math.round(revenue.live)}/mo live revenue maintained`);
  if (workforce.completedThisWeek > 0) topAchievements.push(`Assignments completed by AI teams`);

  const stalledGoals = goals.filter(g => g.stalled);
  if (stalledGoals.length > 0) {
    missedTargets.push(`${stalledGoals.length} goal${stalledGoals.length !== 1 ? "s" : ""} stalled with no progress`);
  }

  if (revenue.atRisk.length > 0) {
    keyLearnings.push(`${revenue.atRisk.length} at-risk pipeline deal${revenue.atRisk.length !== 1 ? "s" : ""} — improve follow-up cadence`);
  }

  if (revenue.fastestPath) {
    nextMonthPriorities.push(`Close: ${revenue.fastestPath.title}`);
  }
  for (const g of goals.filter(g => g.daysToDeadline !== null && g.daysToDeadline < 60)) {
    nextMonthPriorities.push(`Advance: ${g.title}`);
  }

  return {
    generatedAt: now.toISOString(),
    month: monthName,
    summary: `${monthName}: €${Math.round(revenue.live)}/mo live revenue, ${goals.length} active goals, ${workforce.totalActiveAssignments} ongoing assignments.`,
    revenueSnapshot: `Live €${Math.round(revenue.live)}/mo | Pipeline €${Math.round(revenue.pipeline)} | Potential €${Math.round(revenue.potential)} | Total active €${Math.round(revenue.total)}`,
    topAchievements,
    missedTargets,
    keyLearnings,
    nextMonthPriorities,
  };
}
